### PR TITLE
Babel 7 and TypeScript support

### LINKED ISSUE #192: TypeScript migration discussion
Should we consider migrating to TypeScript? It would give us better and stronger types, give us static analysis, and make Snoowrap work better for TypeScript projects. 

It would also allow us to create interfaces for API responses so it is better documented what responses we get, snoowrap wouldn't break if more properties are added to the responses.

There's three things we could do if we do not have anything against it.

1. Migrate existing code to TypeScript incrementally,
2. Create TS definitions for existing classes, or
3. Combination of 1 and 2.

If we agree on migrating to TypeScript we do not need to do it all in one go. We can migrate one file at a time and do so in our own pace. Tests do not need to change. We would still be able to use ESLint given `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` is added

If we agree only on TS definitions, this would be a `.d.ts` file next to every file we currently have which would remove the need for DefinitelyTyped's snoowrap definitions. No changes would need to be made with existing code.

I can create a tracking issue if we agree on any options

### PR DESCRIPTION
**Pull request by SpyTec**
Migration to Babel 7 and addition to TypeScript compilation.

This includes the DefinitelyTyped definitions, Babel 7 core and plugin migration, as well as TypeScript compilation config. Tests run successfully and we can build

Todo:

- [x] Fix snoowrap.d.ts definitions
- [ ] ~~Fix snoowrap-tests.ts - what is it/used for?~~ - We can probably remove this
- [x] Add TypeScript to ESLint
- [x] Check docs generation with TS components - Verified it will not affect docs, the JS files will still be generated with TS files.
- [x] Validate TS compilation `npm run check-types` and that it copies to `/dist`
- [x] Add TS scripts to `npm run compile`
- [x] [Add TS types to `package.json`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)

@markspolakovs thoughts/concerns? Tagging @not-an-aardvark as well since it's more than just a plugin change to the build process

Closes #192

### CODE REVIEW

**Comment by markspolakovs** [comment]
`snoowrap.d.ts` is meant to be used with https://github.com/microsoft/dtslint if I understood it correctly - checking that the type definitions make sense. Could be helpful to set up.

**Comment by markspolakovs** [comment]
Also, you'll want to add the type definitions to `package.json` so that TS can find them: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by SpyTec** [comment]
> 
> 
> `snoowrap-tests.ts` _(edit: derp)_ is meant to be used with [microsoft/dtslint](https://github.com/microsoft/dtslint) if I understood it correctly - checking that the type definitions make sense. Could be helpful to set up.

Gotcha, are people using both TSLint and ESLint together? I thought the ESLint TypeScript plugins is good enough. I'd avoid adding TSLint of we can instead just use an ESLint plugin

> 
> 
> Also, you'll want to add the type definitions to `package.json` so that TS can find them: [typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)

I see, clears things up - added it to the todo list

**Comment by SpyTec** [comment]
I believe all changes needed has been done. We should now support TypeScript files, definition files, Babel 7, ESLint ^6.1.0, and compilation script updated.

I will wait until @not-an-aardvark takes a look since it's a large build change. But feel free to take a lookover once more @markspolakovs. I think we will remove the `snoowrap-tests.ts` though, not sure if it's of any use

**Comment by markspolakovs** [comment]
@SpyTec sorry, didn't see this until now, but nowadays you can use ESLint to lint TS too - see  https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.jsas an example. DTSLint, confusingly enough, is a totally different tool for a different purpose - checking definition files for correctness, while ESLint checks for styling et al

**Comment by SpyTec** [comment]
That's all I wanted to know :)

I'll go ahead and merge this and create tickets to update TS defs for new Modmail

**Comment by markspolakovs** [comment]
PR #200 woo!

**Comment by markspolakovs** [comment]
Once the typedefs are published to npm, the last step is to mark the DefinitelyTyped defs as deprecated following this procedure: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#removing-a-package

**Comment by markspolakovs** [comment]
@SpyTec Since 1.19.0 was released with the TypeScript defs, I'm going to submit a PR to DefinitelyTyped to deprecate `@types/snoowrap` if you don't mind

**Comment by SpyTec** [comment]
@markspolakovs sounds good to me!

**Comment by markspolakovs** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37394

**Pull request merged**
