### PR TITLE
Added EventStream and the ability to get an event stream of new comme…

### PR DESCRIPTION
**Pull request by lobabob**
…nts and submissions.

So I meant to send you this pull request after writing tests for my code, but for some reason I wasn't able to get your existing tests to pass for me. I figured I'd just ask you about it here.

### CODE REVIEW

**Comment by lobabob** [comment]
So I ran your tests and attached the output (in separate stderr and stdout) log files. Could you take a brief look at these? You might see something obvious that I'm missing in terms of getting these tests to run.

If it's helpful, I'm running this on windows (not sure if that affects anything though).

[testLogs.zip](https://github.com/not-an-aardvark/snoowrap/files/770082/testLogs.zip)

**Comment by not-an-aardvark** [comment]
Thanks for the pull request!

My initial impression is that this seems out-of-scope for an API wrapper. I think users might be better off using `setTimeout`/`setInterval` on their own. There are a few reasons for this:

* Using `setTimeout` directly gives users more control over some of the decisions in this PR (e.g. what the period should be, and what to do in the event of an error) rather than being locked into whatever snoowrap does.
* This doesn't use any special features related to the reddit API -- it just calls existing snoowrap functions at an interval. Since snoowrap is intended to just be a wrapper for the reddit API, I don't see the benefit of having built-in functionality to run its functions at an interval, since this is fairly easy to accomplish outside of snoowrap. (This is different from the existing streaming API for reddit livethreads, which uses websockets to stream content directly from reddit.)

Do you have any thoughts on this?

**Comment by lobabob** [comment]
**Error Handling:** I made sure to pass any errors that occurred back out for the user to handle via an error event. 

**`setTimeout` Flexibility:** Looking back over this again, period is kinda unnecessary. The user can just provide a rate in milliseconds directly. I'll update the PR to reflect this.

**Applicability:** Are you intending for this to be a direct 1 to 1 wrapper of the Reddit API? The current state of the repo already fits that. The additions in this request just add some convenience methods to make it easier to consume the existing methods in different forms. I feel that consuming new comments/submissions as they come out is a common enough use case to warrant convenience methods for them.

**Comment by not-an-aardvark** [comment]
Regarding `setTimeout` flexibility, I just don't really see the point of passing polling parameters to snoowrap when one can use `setTimeout` on their own. I don't think it's worth using an extra abstraction.

> Applicability: Are you intending for this to be a direct 1 to 1 wrapper of the Reddit API?

I want this to be a library that makes it easy to work with the reddit API. It's not exactly 1-to-1, since there are some methods that make multiple requests in order to prevent the user from having to deal with some gotchas in the reddit API. But I also want to avoid feature creep in cases where there are easy alternatives to using the proposed feature.

I don't mean to shoot down your work, but I also don't think this is a good feature to add to snoowrap, so I'm going to close this PR. Thanks again for being willing to contribute.

**Comment by lobabob** [comment]
Took your advice and made the feature a stand-alone package: https://www.npmjs.com/package/snoostream

**Pull request closed without merging**
