### PR TITLE
Fix a few issues with Snoowrap#fromApplicationOnlyAuth

### PR DESCRIPTION
**Pull request by a-bravo**
This fixes minor issues (typos) relating to the deviceId param. See the [reddit OAuth wiki](https://github.com/reddit-archive/reddit/wiki/oauth2#application-only-oauth) for deviceId requirements.

### CODE REVIEW

**Comment by SpyTec** [comment]
We can probably remove the exception. Docs suggest 20-30 but also suggests UUID which is 36 characters.

I'm not sure I agree with dropping `DO_NOT_TRACK_THIS_DEVICE` as it's in the [GH Reddit docs](https://github.com/reddit-archive/reddit/wiki/oauth2#application-only-oauth)

> reddit may choose to use this ID to generate aggregate data about user counts. Clients that wish to remain anonymous should use the value DO_NOT_TRACK_THIS_DEVICE.

**Comment by a-bravo** [comment]
> We can probably remove the exception. Docs suggest 20-30 but also suggests UUID which is 36 characters.

Sounds good!

> I'm not sure I agree with dropping `DO_NOT_TRACK_THIS_DEVICE` as it's in the [GH Reddit docs](https://github.com/reddit-archive/reddit/wiki/oauth2#application-only-oauth)

Previously the snoowrap documentation for `clientId` referenced `DO_NOT_TRACK_THIS_DEVICE`. According to the reddit docs, this value is used for `deviceId` (can't find any mention of it for `clientId`). The change moves the reference to the correct param.

**Comment by SpyTec** [comment]
Right ignore me, was being too hasty in my review. Drop the exception check and associated test and I'll merge :)

**Comment by a-bravo** [comment]
I could not find the associated test. Can you point me in the right direction? Thanks!

**Comment by SpyTec** [comment]
Again, my mistake. Thought we had a test for it; Changes look good, I'll go ahead and merge

**Pull request merged**
